FakeBook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls.conf import include
from django.conf.urls.static import static
from . views import home

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('accounts/', include('allauth.urls')),

# These are the path for Api 

    path('api/profile/', include('profilesAPI.urls')),
    path('api/post/', include('postsAPI.urls')),

# These are the path for linking other apps in this projects->>>

    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('posts/',include('posts.urls',namespace='posts')),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# +static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . views import post_comment_create_and_list_view,like_unlike_post,PostDeleteView,PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('',post_comment_create_and_list_view, name ='main-post-view' ),
    path('liked/',like_unlike_post, name ='like-post-view' ),
    path('<pk>/delete/',PostDeleteView.as_view(),name='post-delete'),
    path('<pk>/update/',PostUpdateView.as_view(),name='post-update')
]

profiles/urls.py
from . import views
from django.urls import path

from . views import (
    my_profile,
    invites_received_view,
    invite_profiles_list_view,
    ProfileListView,
    ProfileDetailView,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    search,
      
)


app_name='profiles'

urlpatterns = [

    path('',ProfileListView.as_view(),name='all-profiles-view'),
    path('myprofile/',my_profile,name='my-profile'),
    path('my-invites/',invites_received_view,name='my-invites-view'),
    path('<slug>',ProfileDetailView.as_view(),name='profile-detail-view'),
    path('to-invite/',invite_profiles_list_view,name='invite-profiles-view'),
    path('send-invite/',send_invitation,name='send-invite'),
    path('remove-friend/',remove_from_friends,name='remove-friend'),
    path('my-invite/accept/',accept_invitation,name='accept-invite'),
    path('my-invite/reject/',reject_invitation,name='reject-invite'),
    path('search/' , search , name='search'),
   

]

templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css -->
    <link rel="stylesheet" type="text/css" href="/static/style.css">
    
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    
    <title>FakeBook - {% block title %}{% endblock title %}</title>
  </head>

  <body>
      {% include 'main/navbar.html' %}<br>
    <div class="ui container">
      {% block content %}
      {% endblock content %}
    </div>
    
    {% block scripts %}
    {% endblock scripts %}
   
   <!--Custom js ADD HERE-->
   
    <script type ="text/javascript" src ="/static/main.js"></script>
  
  </body>
</html>

templates/main/home.html
{% extends 'main/base.html' %}
{% block title %}Home{% endblock title %}


{% block content %}
{% if user.is_authenticated %}

<div class="ui success message">
  <i class="close icon"></i>
  <div class="header">
    Login was successful Welcome to FakeBook! {{user}}.
  </div>
  <p>This is a place where you can make friends and socialise your lonely life</p>
</div>

  
{% else %}


<div class="ui success message">
  <i class="close icon"></i>
  <div class="header">
    You are currently not logged in
  </div>
  <p>Please login to view and edit content on the Fakebook network</p>
</div>


{% endif %}
{% endblock content %}

{% block scripts %}
<script>
  
</script>
{% endblock scripts %}

templates/main/navbar.html
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'home' as path_to_home %}
{% url 'profiles:my-profile' as path_to_my_profile %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invite_profiles_view %}

<div class="ui inverted menu nav mb-7">
    <div class="ui container">
      <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
          <h3 style="text-shadow: 0px 5px 5px rgb(63, 62, 62);">Fakebook</h3>
      </a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Timeline
      </a>
      {% endif %}
  
      <div class="right menu">
          {% if request.user.is_authenticated %}
          <div class="item">
              <div class="ui floating dropdown icon button teal"> Friends
                  <i class="dropdown icon"></i>
                  <div class="menu">
                      <a href="{{path_to_all_profiles}}" class="item">
                          All Profiles
                      </a>
                      <a href="{{path_to_invite_profiles_view}}" class="item">
                          Invite friend
                      </a>
                      <a href="{{path_to_my_invites}}" class="item">
                          Friend Requests &nbsp;<div class="ui purple horizontal label">{{invites_num}}</div>
                      </a>
                  </div>
               </div>
          </div>
               <div class="item">
                <form action="{% url 'profiles:search' %}" method="get">
                  <div class="ui action left icon input">
                  <input class="prompt" type="search" name='query'  placeholder="name of a person...">
                  <i class="search icon"></i>
                  <button type='submit' class="ui button">Search</button>
                  </div>
              </form>
              </div>
          
              <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                  <img src="{{picture.url}}" alt="Logged in user picture" class ="ui avatar image">
                  {{ request.user }}
              </a>
  
              <a href="{% url 'account_logout' %}" class="ui item">
                  Logout
              </a>
          {% else %}
          <a href="{% url 'account_login' %}" class="ui item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
  </div>