FakeBook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls.conf import include
from django.conf.urls.static import static
from . views import home

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('accounts/', include('allauth.urls')),

# These are the path for Api 

    path('api/profile/', include('profilesAPI.urls')),
    path('api/post/', include('postsAPI.urls')),

# These are the path for linking other apps in this projects->>>

    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('posts/',include('posts.urls',namespace='posts')),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# +static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . views import post_comment_create_and_list_view,like_unlike_post,PostDeleteView,PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('',post_comment_create_and_list_view, name ='main-post-view' ),
    path('liked/',like_unlike_post, name ='like-post-view' ),
    path('<pk>/delete/',PostDeleteView.as_view(),name='post-delete'),
    path('<pk>/update/',PostUpdateView.as_view(),name='post-update')
]

profiles/urls.py
from . import views
from django.urls import path

from . views import (
    my_profile,
    invites_received_view,
    invite_profiles_list_view,
    ProfileListView,
    ProfileDetailView,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    search,
      
)


app_name='profiles'

urlpatterns = [

    path('',ProfileListView.as_view(),name='all-profiles-view'),
    path('myprofile/',my_profile,name='my-profile'),
    path('my-invites/',invites_received_view,name='my-invites-view'),
    path('<slug>',ProfileDetailView.as_view(),name='profile-detail-view'),
    path('to-invite/',invite_profiles_list_view,name='invite-profiles-view'),
    path('send-invite/',send_invitation,name='send-invite'),
    path('remove-friend/',remove_from_friends,name='remove-friend'),
    path('my-invite/accept/',accept_invitation,name='accept-invite'),
    path('my-invite/reject/',reject_invitation,name='reject-invite'),
    path('search/' , search , name='search'),
   

]

profiles/models.py
from typing import BinaryIO
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.urls import reverse

# Create your models here.

#############################################################################################################

class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self,sender):

        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        # Above we need to check two cases where sender is our profile or the receiver is our profile

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)

        available = [profile for profile in profiles if profile not in accepted]

        # above we need to exclude all profiles where rel = accepted and also select all profiles where only we are excluded
        # Here we used list comprehension method = newList = "[ expression(element) for element in oldList if condition ]"
        # to avoid long loops.

        print(available)
        return available

    def get_all_profiles(self,me):

        profiles= Profile.objects.all().exclude(user=me)
        return profiles

#############################################################################################################

class Profile(models.Model):

    first_name = models.CharField(max_length=200,blank=True)
    last_name = models.CharField(max_length=200,blank=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    Bio = models.TextField(default='no bio ...',max_length=300)
    email = models.EmailField(max_length=200,blank=True)
    dob = models.DateField(blank=True,null=True)
    country = models.CharField(max_length=100,blank=True)
    avatar = models.ImageField(default = 'profile/images/avatar.png',upload_to="profile/images")
    friends = models.ManyToManyField(User,blank=True,related_name='friends')
    slug = models.SlugField(unique=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now =True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}"

    def get_absolute_url(self):
        return reverse("profiles:profile-detail-view",kwargs={'slug':self.slug})

    def get_friends(self):
        return self.friends.all()
    
    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()    # author we named to posts

    def get_all_authors_post(self):
        return self.posts.all()
    
    def get_likes_given_no(self):
        likes = self.like_set.all()      # since related name to Like is not given
        total_liked = 0
        for item in likes:
            if item.value =='Like':
                total_liked += 1
        return total_liked

    def get_likes_received_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()    # object name 'liked' used instead of related name 'likes' because has no reverse relationship
        return total_liked

    
    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self. __initial_first_name = self.first_name
        self. __initial_last_name = self.last_name

    def save(self,*args, **kwargs):
        ex=False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name and self.last_name != self.__initial_last_name or self.slug =="":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name)+ " " +str(self.last_name))
                ex=Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " +str(get_random_code()))
                    ex=Profile.objects.filter(slug=to_slug).exists()
            else:
                 to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)



#############################################################################################################


STATUS_CHOICES = (
    ('send','send'),
    ('accepted','accepted')
)

class RelationshipManager(models.Manager):

    def invitations_received(self,receiver):
        qs = Relationship.objects.filter(receiver=receiver,status="send")
        return qs
        
        # instead of writing in views "Relationship.objects.filter()"" we now will write "Relationship.objects.invitations_received"

#############################################################################################################


class Relationship(models.Model):

    sender = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='sender')
    receiver = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='receiver')
    status = models.CharField(max_length=8,choices=STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects =RelationshipManager()

    def __str__(self):
        return str(self.sender)+"  "+str(self.receiver)+ "  " +str(self.status)


#############################################################################################################

profiles/forms.py
from django import forms
from django.forms import ModelForm
from .models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name','last_name','dob','Bio','country','avatar')

profiles/views.py
from django.http.response import JsonResponse
from django.shortcuts import render ,redirect,get_object_or_404
from.models import Profile,Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView,DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

###########################################################################################################

@login_required
def my_profile(request):

    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None , request.FILES or None,instance=profile)
    confirm =False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm=True

    context={'profile':profile,'form':form,'confirm':confirm}

    return render(request,'profile/myprofile.html',context)

#############################################################################################################

@login_required
def invites_received_view(request):

    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitations_received(profile)
    results =list(map(lambda x: x.sender,qs))

    is_empty=False
    if len(results) == 0:
        is_empty = True

    context={'qs':results,'is_empty':is_empty}

    return render(request,'profile/my_invites.html',context)

#############################################################################################################

@login_required
def accept_invitation(request):

    if request.method == 'POST':
        pk =request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship,sender=sender,receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:my-invites-view')

#############################################################################################################

@login_required
def reject_invitation(request):

    if request.method == 'POST':
        pk =request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship,sender=sender,receiver=receiver)
        rel.delete()
    return redirect('profiles:my-invites-view')

#############################################################################################################

@login_required
def profiles_list_view(request):

    user = request.user
    qs = Profile.objects.get_all_profiles(user)

    # qs =Profile.objects.all().exclude(user=user)    <---- Also we can use this way to define it

    context={'qs':qs}

    return render(request,'profile/profile_list.html',context)

#############################################################################################################

@login_required
def invite_profiles_list_view(request):

    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)
    profile = Profile.objects.get(user=user)

    rel_r = Relationship.objects.filter(sender=profile)
    rel_s = Relationship.objects.filter(receiver=profile)

    rel_receiver = []
    rel_sender = [] 

    for item in rel_r:
        rel_receiver.append(item.receiver.user)
    for item in rel_s:
        rel_sender.append(item.sender.user)

    context={'qs':qs,'rel_sender':rel_sender,'rel_receiver':rel_receiver}

    return render(request,'profile/to_invite_list.html',context)

#############################################################################################################


class ProfileDetailView(LoginRequiredMixin,DetailView):
    
    model = Profile
    template_name = 'profile/detail.html'

    def get_object(self,slug=None):

        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs): 

        context = super().get_context_data(**kwargs)
        user = User.objects.get(username = self.request.user)
        profile = Profile.objects.get(user=user)

        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)

        rel_receiver = []
        rel_sender = [] 

        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)

        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context["posts"] = self.get_object().get_all_authors_post()
        context["len_posts"] = True if len(self.get_object().get_all_authors_post()) > 0 else False
        return context

#############################################################################################################   


class ProfileListView(LoginRequiredMixin,ListView):
    
    model = Profile
    paginate_by = 3
    template_name = 'profile/profile_list.html'
    context_object_name = 'qs'  # default in django gives item in object_list

    def get_queryset(self):

        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs): 

        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact = self.request.user)

        #name__iexact means that you are doing a case insensitive match on the field name.

        profile = Profile.objects.get(user=user)

        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)

        rel_receiver = []
        rel_sender = [] 

        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)

        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context["is_empty"] = False

        if len(self.get_queryset()) == 0:
            context["is_empty"] = True

        return context

#############################################################################################################


@login_required
def send_invitation(request):

    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender,receiver=receiver,status='send')
        return redirect(request.META.get ('HTTP_REFERER'))
    
    return redirect('profiles:my-profile')

#############################################################################################################

@login_required
def remove_from_friends(request):

    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(( Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender)) )
        rel.delete()
        return redirect(request.META.get ('HTTP_REFERER'))
    return redirect('profiles:my-profile')

#############################################################################################################

@login_required
def search(request):

    query=request.GET['query']
    res=Profile.objects.filter(Q(slug__icontains=query) | Q(first_name__icontains=query)).exclude(user=request.user)
    
    user = User.objects.get(username = request.user)
    profile = Profile.objects.get(user=user)

    rel_r = Relationship.objects.filter(sender=profile)
    rel_s = Relationship.objects.filter(receiver=profile)

    rel_receiver = []
    rel_sender = [] 

    for item in rel_r:
        rel_receiver.append(item.receiver.user)
    for item in rel_s:
        rel_sender.append(item.sender.user)

    context={'res':res,'rel_receiver':rel_receiver,'rel_sender':rel_sender}
    return render(request,"profile/search.html",context)

#############################################################################################################

profiles/templates/profile/detail.html
{% extends 'main/base.html' %}
{% block title %}Profile|detail{% endblock title %}

{% block content %}

<div class="ui grid">
    <div class="row">

        <div class="four wide column">
            <img class = "ui medium rounded image" src="{{object.avatar.url}}" alt="">
            <h2>{{object.user}}</h2>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{object.get_posts_no}}</div>
                </div>
                <div class="item">
                    Likes Given
                    <div class="ui label">{{object.get_likes_given_no}}</div>
                </div>
                <div class="item">
                    Likes Received
                    <div class="ui label">{{object.get_likes_received_no}}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{object.get_friends_no}}</div>
                </div>
            </div>

                {% if object.user not in rel_receiver and object.user not in rel_sender %}
                    <form action="{% url 'profiles:send-invite' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{object.pk}}>
                        <button class="ui positive basic button mb-5 w-big" type="submit">
                            <i class="plus square icon"></i>Add to friends
                        </button>
                    </form>
                    {% endif %}

                    {% if object.user in rel_receiver and object.user not in object.friends.all %}
                    <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                    {% endif %}

                    {% if request.user in object.friends.all %}
                    <form action="{% url 'profiles:remove-friend' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{object.pk}}>
                        <button class="ui negetive basic button mb-5 w-big" type="submit">
                            <i class="minus square icon"></i>Remove friend
                        </button>
                    </form>
                    {% endif %}

           
        </div>

        <div class="twelve wide columns">
            {% if len_posts %}
            {% for post in posts %}
            <div class="segment ui fluid">
                {{post.content}}
            </div>
            {% endfor %}
            {% else %}
            <h2>This user dont own any posts..</h2>
            {% endif %}
        </div>
        
    </div>
</div>

{% endblock content %}

profiles/templates/profile/my_invites.html
{% extends 'main/base.html' %}
{% block title %}MyInvites{% endblock title %}

{% block content %}

{% if is_empty %}
<div class="ui floating message">
    <p>You do not have any invitations yet...</p>
</div>
{% endif %}

    {% for item in qs %}

   
    <!-- <div class="ui cards">
        <div class="card">
          <div class="content">
            <img class="right floated ui small image" src="{{item.avatar.url}}">
            <a href="{{item.get_absolute_url}}">
            <div class="header">
                {{item.user}}
            </div></a>
            <div class="meta">
              {{ item.user.first_name }}            
            </div>
            <div class="description">
              Wants to be your friend on Fakebook
            </div>
          </div>
          <div class="extra content">
            
                <a href="{{item.get_absolute_url}}">
                    <button class="ui primary button mb-5 w-big">See profile</button>
                </a>

                <form action="{% url 'profiles:accept-invite' %}" method="POST">
                    {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{item.pk}}>
                    <button class="ui positive basic button mb-5 w-big" type="submit">
                        <i class="check icon"></i>Approve
                    </button>
                </form>
                <form action="{% url 'profiles:reject-invite' %}" method="POST">
                    {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{item.pk}}>
                    <button class="ui negetive basic button mb-5 w-big" type="submit">
                        <i class="close icon"></i>Decline
                    </button>
                </form>
           
          </div>
        </div> -->
  
       


    <div class="ui segment">
        <div class=" ui grid">
            <div class="row">
                <div class="three wide column">
                    <img class = "ui small circular image" src="{{item.avatar.url}}" alt="">
                </div>
                <div class="thirteen wide column">

                    <h3>{{item.user}}</h3>
                    <p>{{item.Bio}}</p><br>

                    <a href="{{item.get_absolute_url}}">
                        <button class="ui primary button mb-5 w-big">See profile</button>
                    </a>

                    <form action="{% url 'profiles:accept-invite' %}" method="POST">
                        {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{item.pk}}>
                        <button class="ui positive basic button mb-5 w-big" type="submit">
                            <i class="check icon"></i>Accept invite
                        </button>
                    </form>

                    <form action="{% url 'profiles:reject-invite' %}" method="POST">
                        {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{item.pk}}>
                        <button class="ui negetive basic button mb-5 w-big" type="submit">
                            <i class="close icon"></i>Reject invite
                        </button>
                    </form>

                </div>
            </div>
        </div>
    </div>

    {% endfor %}

{% endblock content %}

profiles/templates/profile/profile_list.html
{% extends 'main/base.html' %}
{% block title %}All Profiles{% endblock title %}
<style>
    .ui segment{
        background-color: #3a3b3c !important;
    }
</style>
{% block content %}

{% if is_empty %}
<h1>No profiles to interact with </h1>
{% endif %}

<ul>
    {% for item in qs %}

    <div class="ui segment">
        <div class="ui grid">
            <div class="row">
                <div class="three wide column">

                    <img class="ui small circular image " src="{{ item.avatar.url }}">

                </div>
                <div class="thirteen wide column">
                    <h3>{{item.user}}</h3>
                    <p>{{item.Bio}}</p>
                    <a href="{{item.get_absolute_url}}">
                    <button class="ui primary button mb-5 w-big">See profile</button></a>
                    <br>

                    {% if item.user not in rel_receiver and item.user not in rel_sender %}
                    <form action="{% url 'profiles:send-invite' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{item.pk}}>
                        
                        <button class="ui positive basic button mb-5 w-big" type="submit">
                            <i class="plus square icon"></i>Add to friends
                        </button>
                    </form>
                    {% endif %}

                    {% if item.user in rel_receiver and request.user not in item.friends.all %}
                    <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                    {% endif %}

                    {% if request.user in item.friends.all %}
                    <form action="{% url 'profiles:remove-friend' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{item.pk}}>
                        <button class="ui negetive basic button mb-5 w-big" type="submit">
                            <i class="minus square icon"></i>Remove friend
                        </button>
                    </form>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

    {% endfor %}
</ul>

<div class="ui one column stackable center aligned page grid">
    <div class="column sixteen wide">

 <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <button class="cmt_btn ui button mb-5"> <a href="{% url 'profiles:all-profiles-view'%}?page=1">&laquo; first</a></button>
        <button class="cmt_btn ui button mb-5"> <a href="{% url 'profiles:all-profiles-view'%}?page={{ page_obj.previous_page_number }}">previous</a></button>
        {% endif %}

        <span class="current">
        
          <strong>{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</strong>  
        
        </span>

        {% if page_obj.has_next %}
        <button class="cmt_btn ui button mb-5"><a href="{% url 'profiles:all-profiles-view'%}?page={{ page_obj.next_page_number }}">next</a></button>
        <button class="cmt_btn ui button mb-5"><a href="{% url 'profiles:all-profiles-view'%}?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></button>
        {% endif %}
    </span>
</div>
</div></div>

{% endblock content %}

profiles/templates/profile/search.html
{% extends 'main/base.html' %}
{% block title %}Search|Results{% endblock title %}

{% block content %}


<ul>
    {% for item in res %}

    <div class="ui segment">
        <div class="ui grid">
            <div class="row">
                <div class="three wide column">

                    <img class="ui small circular image " src="{{ item.avatar.url }}">

                </div>
                <div class="thirteen wide column">
                    <h3>{{item.user}}</h3>
                    <p>{{item.Bio}}</p>
                    <a href="{{item.get_absolute_url}}">
                    <button class="ui primary button mb-5 w-big">See profile</button></a>
                    <br>

                    {% if item.user not in rel_receiver and item.user not in rel_sender %}
                    <form action="{% url 'profiles:send-invite' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{item.pk}}>
                        
                        <button class="ui positive basic button mb-5 w-big" type="submit">
                            <i class="plus square icon"></i>Add to friends
                        </button>
                    </form>
                    {% endif %}

                    {% if item.user in rel_receiver and request.user not in item.friends.all %}
                    <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                    {% endif %}

                    {% if request.user in item.friends.all %}
                    <form action="{% url 'profiles:remove-friend' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{item.pk}}>
                        <button class="ui negetive basic button mb-5 w-big" type="submit">
                            <i class="minus square icon"></i>Remove friend
                        </button>
                    </form>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

    {% endfor %}
</ul>

{% endblock content %}

profiles/templates/profile/to_invite_list.html
{% extends 'main/base.html' %}
{% block title %}Invite Friends{% endblock title %}

{% block content %}


{% for item in qs %}

{% if item.user not in rel_receiver and item.user not in rel_sender %}
<div class="ui segment">
    <div class=" ui grid">
        <div class="row">
            <div class="three wide column">
                <img class="ui small circular image" src="{{item.avatar.url}}" alt="">
            </div>
            <div class="thirteen wide column">

                <h3>{{item.user}}</h3>
                <p>{{item.Bio}}</p><br>

                <a href="{{item.get_absolute_url}}">
                    <button class="ui primary button mb-5 w-big">See profile</button>
                </a>

                <form action="{% url 'profiles:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{item.pk}}>

                    <button class="ui positive basic button mb-5 w-big" type="submit">
                        <i class="plus square icon"></i>Add to friends
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{% elif item.user in rel_receiver and request.user not in item.friends.all %}


<div class="ui segment">
    <div class=" ui grid">
        <div class="row">
            <div class="three wide column">
                <img class="ui small circular image" src="{{item.avatar.url}}" alt="">
            </div>
            <div class="thirteen wide column">

                <h3>{{item.user}}</h3>
                <p>{{item.Bio}}</p><br>

                <a href="{{item.get_absolute_url}}">
                    <button class="ui primary button mb-5 w-big">See profile</button>
                </a><br>

                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>

            </div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}


{% endblock content %}